spring:
  application:
    name: SERVER

  datasource:
    url: jdbc:mysql://localhost:3306/orderease
    username: root
    password: tiger
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true